# Generated by Django 5.2.4 on 2025-07-28 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('installs', models.BigIntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=50, null=True)),
                ('current_ver', models.CharField(blank=True, max_length=50, null=True)),
                ('android_ver', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('translated_review', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment_polarity', models.FloatField(blank=True, null=True)),
                ('sentiment_subjectivity', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.app')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
